### PR TITLE
update to 5.3.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Alternative to #7

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by damianavila** [comment]
Thanks @ocefpaf

**Comment by damianavila** [comment]
Quick question, I don't see win32 nor linux-32 packages... that is intended by the matrix specification?
Are you not supporting building 32 packages anymore?

**Comment by ocefpaf** [comment]
Conda-forge never had Linux32 and we deprecated Win32 a few months ago due to CI resources constraint. However, now that AnacondaInc is fetching most of their recipes from `conda-forge`, there is a change they pick this one up and build it for all the platforms they support, which includes both Linux 32 and Windows 32.

**Comment by damianavila** [comment]
Thanks for the context!

**Pull request merged**
