### PR TITLE
Release 5.3.0 and some dependencies corrections. Also adding maintainers

### PR DESCRIPTION
**Pull request by damianavila**
@ocefpaf, this PR corresponds to the next RISE release.

I did some minor modifications to the recipe.

One question, I see you use `python -m pip install --no-deps --ignore-installed .` in line 14... is this the accepted standard? In the past, I have used `python setup.py install` but IIRC the better option was being discussed in some issue (I don't have the reference right now).

Finally, adding me (and others) as a maintainer is the only thing needed to have merge rights on this repo?

### CODE REVIEW

**Comment by damianavila** [comment]
@ocefpaf, py27 is failing with this error:

```
 rise requires Python '>=2.7,>=3.4' but the running Python is 2.7.15
```

Certainly, 2.7.15 is bigger than 2.7... did you see something like this somewhere else?

**Comment by damianavila** [comment]
Re-rendering the feedstock does not help.

**Comment by ocefpaf** [comment]
> Certainly, 2.7.15 is bigger than 2.7... did you see something like this somewhere else?

That is odd. Not sure it has anything to do with conda-forge's CI infrastructure, so re-rendering won't help. That message seems to be from `conda-build` and not `rise` itself, right? @msarahan do you have any clues of what may be happening here?

**Comment by ocefpaf** [comment]
@damianavila the issue is in `rise`'s `setup.py` we cannot have two `>=`. I'm preparing a patch for the recipe and, if things work, I'll upstream it.

**Pull request closed without merging**
